"use client";
import {useEffect,useState} from 'react';
import {request,requestWithMeta,formatUserFacingError} from './api-client';
import {TeacherMediaPreview} from './teacher-media-preview';
import type {AdminLocale} from './admin-types';
type RecordRow={id:string;studentName:string;studentNumber:string;className:string;businessDate:string;sportName:string|null;sportType:string;actualDurationSeconds:number;creditedDurationSeconds:number;workflowStage?:string;recordOrigin?:string;currentReview:{result:string;publicComment:string|null}|null};
function Evidence({id}:{id:string}){const [ids,setIds]=useState<string[]>([]),[error,setError]=useState('');useEffect(()=>{let live=true;void request<{mediaIds:string[]}>(`/exercise-records/${id}/evidence-context`).then(value=>{if(live)setIds(value.mediaIds);}).catch(e=>{if(live)setError(formatUserFacingError(e));});return()=>{live=false;};},[id]);return <div>{error&&<p role="alert">{error}</p>}{ids.map(mediaId=><TeacherMediaPreview key={mediaId} mediaId={mediaId} label="打卡凭证"/>)}</div>;}
export function AdminCheckins({locale}:{locale:AdminLocale}){
 const zh=locale==='zh';const [rows,setRows]=useState<RecordRow[]>([]),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [cursor,setCursor]=useState<string|undefined>(),[history,setHistory]=useState<(string|undefined)[]>([]),[next,setNext]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState<string|null>(null);
 useEffect(()=>{let live=true;setBusy(true);setError('');setOpen(null);const p=new URLSearchParams({limit:'25',sort:'-businessDate'});if(query)p.set('q',query);if(from)p.set('businessDateFrom',from);if(to)p.set('businessDateTo',to);if(cursor)p.set('cursor',cursor);
 void requestWithMeta<RecordRow[]>(`/exercise-records?${p}`).then(result=>{if(live){setRows(result.data);setNext(result.meta.pagination?.nextCursor??null);}}).catch(e=>{if(live){setRows([]);setError(formatUserFacingError(e));}}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[query,from,to,cursor]);
 const reset=()=>{setCursor(undefined);setHistory([]);};
 const labels:Record<string,string>={VALID:zh?'有效':'Valid',INVALID:zh?'无效':'Invalid',PENDING:zh?'待教师审核':'Pending review',DRAFT:zh?'草稿':'Draft'};
 return <section className="admin-panel admin-checkins"><h2>{zh?'所有学生打卡记录':'Student exercise records'}</h2><form className="admin-outbox-filters" onSubmit={e=>{e.preventDefault();reset();setQuery(search.trim());}}><label>{zh?'姓名 / 学号 / 运动项目':'Name / student number / sport'}<input value={search} onChange={e=>setSearch(e.target.value)} maxLength={200}/></label><label>{zh?'开始日期':'From'}<input type="date" value={from} onChange={e=>{reset();setFrom(e.target.value);}}/></label><label>{zh?'结束日期':'To'}<input type="date" value={to} onChange={e=>{reset();setTo(e.target.value);}}/></label><button className="secondary-button" disabled={busy}>{zh?'查询':'Search'}</button></form>
 {error&&<p role="alert">{error}</p>}{busy&&<p role="status">{zh?'正在加载…':'Loading…'}</p>}
 <div className="table-scroll"><table><thead><tr>{(zh?['学生','课程 / 日期','运动','实际 / 有效分钟','审核结果','凭证']:['Student','Class / date','Sport','Actual / credited minutes','Review','Evidence']).map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id}><td>{row.studentName}<small className="table-sub">{row.studentNumber}</small></td><td>{row.className}<small className="table-sub">{row.businessDate}</small></td><td>{row.sportName??({RUNNING:zh?'跑步':'Running',SWIMMING:zh?'游泳':'Swimming',WALKING:zh?'步行':'Walking'}[row.sportType]??row.sportType)}{row.recordOrigin==='HISTORICAL'&&<small className="table-sub">{zh?'历史补录':'Past exercise'}</small>}</td><td>{Math.floor(row.actualDurationSeconds/60)} / {row.creditedDurationSeconds/60}</td><td>{labels[row.currentReview?.result??'DRAFT']??row.workflowStage}<small className="table-sub">{row.currentReview?.publicComment}</small></td><td><button className="secondary-button" type="button" onClick={()=>setOpen(open===row.id?null:row.id)}>{zh?'查看凭证':'View evidence'}</button>{open===row.id&&<Evidence id={row.id}/>}</td></tr>)}</tbody></table></div>
 {!busy&&!rows.length&&!error&&<p>{zh?'没有符合条件的记录。':'No matching records.'}</p>}<button className="secondary-button" disabled={busy||!history.length} onClick={()=>{setCursor(history.at(-1));setHistory(v=>v.slice(0,-1));}}>{zh?'上一页':'Previous'}</button><button className="secondary-button" disabled={busy||!next} onClick={()=>{setHistory(v=>[...v,cursor]);setCursor(next??undefined);}}>{zh?'下一页':'Next'}</button></section>;
}
