"use client";
import {useEffect,useState} from 'react';
import {request,requestWithMeta,formatUserFacingError} from './api-client';
import {TeacherMediaPreview} from './teacher-media-preview';
import {businessDateTime} from './business-time';
import type {AdminLocale} from './admin-types';
type RecordRow={id:string;studentId:string;studentName:string;studentNumber:string;className:string;businessDate:string;startedAt?:string;endedAt?:string;submittedAt:string|null;sportName:string|null;sportType:string;actualDurationSeconds:number;creditedDurationSeconds:number;workflowStage?:string;recordOrigin?:string;currentReview:{result:string;publicComment:string|null}|null};
function Evidence({id}:{id:string}){const [ids,setIds]=useState<string[]>([]),[error,setError]=useState('');useEffect(()=>{let live=true;void request<{mediaIds:string[]}>(`/exercise-records/${id}/evidence-context`).then(value=>{if(live)setIds(value.mediaIds);}).catch(e=>{if(live)setError(formatUserFacingError(e));});return()=>{live=false;};},[id]);return <div className="checkin-evidence-gallery">{error&&<p role="alert">{error}</p>}{ids.map(mediaId=><TeacherMediaPreview key={mediaId} mediaId={mediaId} label="打卡凭证"/>)}</div>;}
const stages:Record<string,string>={VALID:'有效',INVALID:'无效',PENDING_TEACHER:'待教师审核',PENDING_AI:'AI 处理中',AWAITING_SUPPLEMENT:'待补充',TECHNICAL:'技术异常'};
const sports:Record<string,string>={RUNNING:'跑步',SWIMMING:'游泳',WALKING:'步行',BASKETBALL:'篮球',FOOTBALL:'足球',BADMINTON:'羽毛球',TABLE_TENNIS:'乒乓球',CYCLING:'骑行',FITNESS:'健身',OTHER:'其他'};
export function AdminCheckins({locale,classSectionId,studentId}:{locale:AdminLocale;classSectionId?:string;studentId?:string}){
 const zh=locale==='zh';const [rows,setRows]=useState<RecordRow[]>([]),[search,setSearch]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState('');
 const [page,setPage]=useState(1),[total,setTotal]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[open,setOpen]=useState<string|null>(null),[view,setView]=useState('list');
 const [stage,setStage]=useState(''),[sport,setSport]=useState(''),[credit,setCredit]=useState(''),[section,setSection]=useState(classSectionId??''),[classes,setClasses]=useState<{id:string;courseName:string}[]>([]);
 useEffect(()=>{setSection(classSectionId??'');setPage(1);},[classSectionId,studentId]);
 useEffect(()=>{if(classSectionId)return;let live=true;void request<{rows:{id:string;courseName:string}[]}>('/admin/course-directory').then(v=>{if(live)setClasses(v.rows);}).catch(e=>{if(live)setError(formatUserFacingError(e));});return()=>{live=false;};},[classSectionId]);
 useEffect(()=>{let live=true;setBusy(true);setError('');setOpen(null);const p=new URLSearchParams({limit:'25',sort:'-businessDate',page:String(page)});for(const [key,value] of Object.entries({q:query,businessDateFrom:from,businessDateTo:to,classSectionId:section,studentId:studentId??'',workflowStage:stage,sportType:sport,creditType:credit}))if(value)p.set(key,value);
 void requestWithMeta<RecordRow[]>(`/exercise-records?${p}`).then(result=>{if(live){setRows(result.data);setTotal(result.meta.pagination?.total??0);}}).catch(e=>{if(live){setRows([]);setError(formatUserFacingError(e));}}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[query,from,to,page,section,studentId,stage,sport,credit]);
 const pages=Math.max(1,Math.ceil(total/25));const change=(setter:(v:string)=>void,value:string)=>{setPage(1);setter(value);};
 const details=(r:RecordRow)=><><b>{r.sportName||sports[r.sportType]||r.sportType}</b><small className="table-sub">{r.recordOrigin==='HISTORICAL'?'历史补录 · ':''}{businessDateTime(r.startedAt)||r.businessDate} → {businessDateTime(r.endedAt)||'未记录结束时间'}</small><small className="table-sub">提交：{businessDateTime(r.submittedAt)||'未提交'}（北京时间）</small><small className="table-sub">实际 {Math.floor(r.actualDurationSeconds/60)} 分 {r.actualDurationSeconds%60} 秒 / 有效 {r.creditedDurationSeconds/60} 分钟</small></>;
 return <section className="admin-panel admin-checkins">{!studentId&&<h2>{zh?'学生打卡记录':'Student exercise records'}</h2>}<form className="admin-outbox-filters checkin-filter-panel" onSubmit={e=>{e.preventDefault();change(setQuery,search.trim());}}><label>{studentId?'搜索运动项目':'姓名 / 学号 / 运动项目'}<input value={search} onChange={e=>setSearch(e.target.value)} maxLength={200}/></label>{!classSectionId&&<label>班级<select value={section} onChange={e=>change(setSection,e.target.value)}><option value="">全部班级</option>{classes.map(c=><option key={c.id} value={c.id}>{c.courseName}</option>)}</select></label>}<label>开始日期<input type="date" value={from} onChange={e=>change(setFrom,e.target.value)}/></label><label>结束日期<input type="date" value={to} min={from} onChange={e=>change(setTo,e.target.value)}/></label><label>审核状态<select value={stage} onChange={e=>change(setStage,e.target.value)}><option value="">全部状态</option>{Object.entries(stages).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>运动类型<select value={sport} onChange={e=>change(setSport,e.target.value)}><option value="">全部运动</option>{Object.entries(sports).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>学时类别<select value={credit} onChange={e=>change(setCredit,e.target.value)}><option value="">全部类别</option><option value="COURSE_RELATED">课程相关</option><option value="GENERAL">其他运动</option></select></label><div className="checkin-filter-actions"><button className="secondary-button" disabled={busy}>查询</button><button className="secondary-button" type="button" disabled={busy} onClick={()=>{setSearch('');setQuery('');setFrom('');setTo('');setStage('');setSport('');setCredit('');setSection(classSectionId??'');setPage(1);}}>重置</button></div></form>
 <div className="checkin-results-toolbar"><span>打卡记录 <b>{total}</b> 条</span><div className="checkin-view-switch"><button className="secondary-button" onClick={()=>setView('list')} aria-pressed={view==='list'}>记录列表</button><button className="secondary-button" onClick={()=>setView('album')} aria-pressed={view==='album'}>凭证相册</button></div></div>
 {error&&<p role="alert">{error}</p>}{busy&&<p role="status">正在加载…</p>}
 {!busy&&view==='list'&&<div className="table-scroll"><table className="admin-table"><thead><tr>{['学生','班级','运动 / 时间','审核结果','凭证'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.studentName}<small className="table-sub">{r.studentNumber}</small></td><td>{r.className}</td><td>{details(r)}</td><td>{stages[r.workflowStage??'']??r.currentReview?.result??'草稿'}<small className="table-sub">{r.currentReview?.publicComment}</small></td><td><button className="secondary-button" type="button" onClick={()=>setOpen(open===r.id?null:r.id)}>查看凭证</button>{open===r.id&&<Evidence id={r.id}/>}</td></tr>)}</tbody></table></div>}
 {!busy&&view==='album'&&<div className="admin-record-albums">{rows.map(r=><article className="admin-surface" key={r.id}>{!studentId&&<h3>{r.studentName} · {r.studentNumber}</h3>}{details(r)}<p className="checkin-status" data-stage={r.workflowStage}>{stages[r.workflowStage??'']??r.currentReview?.result}</p><Evidence id={r.id}/></article>)}</div>}
 {!busy&&!rows.length&&!error&&<p>没有符合条件的记录。</p>}<div className="admin-pagination"><span>第 {page} / {pages} 页 · 共 {total} 条 · 每页 25 条</span><div><button disabled={busy||page<=1} onClick={()=>setPage(1)}>首页</button><button disabled={busy||page<=1} onClick={()=>setPage(v=>v-1)}>上一页</button><label>跳转页码 <input aria-label="跳转页码" type="number" min={1} max={pages} value={page} style={{width:80}} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=pages)setPage(n);}}/></label><button disabled={busy||page>=pages} onClick={()=>setPage(v=>v+1)}>下一页</button><button disabled={busy||page>=pages} onClick={()=>setPage(pages)}>末页</button></div></div></section>;
}
