"use client";
import {useEffect,useRef,useState} from 'react';
import {request,formatUserFacingError} from './api-client';
import {businessDateTime} from './business-time';
type Bucket={label:string;value:number};
type Insights={generatedAt:string;from:string;to:string;summary:{records:number;students:number;seconds:number;credited:number};daily:Bucket[];sports:Bucket[];stages:Bucket[];frequency:Bucket[];classes:Bucket[];teachers:Bucket[];heatmap:{weekday:number;hour:number;value:number}[]};
const stageLabels:Record<string,string>={VALID:'有效',INVALID:'无效',PENDING_TEACHER:'待教师审核',PENDING_AI:'AI 处理中',TECHNICAL:'技术异常',AWAITING_SUPPLEMENT:'待补充',UNKNOWN:'未记录流程状态'};
const sportLabels:Record<string,string>={RUNNING:'跑步',SWIMMING:'游泳',BADMINTON:'羽毛球',TABLE_TENNIS:'乒乓球',BASKETBALL:'篮球',FOOTBALL:'足球',FITNESS:'健身',CYCLING:'骑行',WALKING:'步行',OTHER:'其他'};
function download(name:string,content:string,type:string){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const chartColors=['#247b72','#76aaa0','#d9b16a','#7b91b5','#ad9bc0','#b3c8c0','#d08772'];
function Chart({title,rows,note,context,kind='bars'}:{title:string;rows:Bucket[];note:string;context:string;kind?:'bars'|'trend'|'donut'|'histogram'}) {
 const ref=useRef<SVGSVGElement>(null),max=Math.max(1,...rows.map(r=>r.value)),total=rows.reduce((n,r)=>n+r.value,0),height=kind==='bars'?Math.max(210,rows.length*38+60):300;
 const [expanded,setExpanded]=useState(false);
 const shown=kind==='bars'&&!expanded?rows.slice(0,8):rows;
 const chartHeight=kind==='bars'?Math.max(210,shown.length*38+60):height;
 const point=(r:Bucket,i:number)=>`${58+i/Math.max(1,rows.length-1)*646},${230-r.value/max*170}`;
 let cumulative=0;
 return <section className={`insights-card insights-chart insights-${kind}`}><div className="insights-card-heading"><div><span className="insights-eyebrow">{kind==='trend'?'ACTIVITY TREND':kind==='donut'?'ACTIVITY MIX':'ACTIVITY BREAKDOWN'}</span><h3>{title}</h3></div><button className="insights-export" disabled={!rows.length} onClick={()=>{if(ref.current)download(`${title}.svg`,new XMLSerializer().serializeToString(ref.current),'image/svg+xml');}} title="导出矢量图表">导出 ↗</button></div><p className="insights-note">{note}</p>{rows.length&&total>0?<div className="insights-chart-scroll"><svg ref={ref} xmlns="http://www.w3.org/2000/svg" viewBox={`0 0 760 ${chartHeight}`} role="img" aria-label={title} style={{width:'100%',background:'#fff',fontFamily:'Arial, Microsoft YaHei, sans-serif'}}><title>{title} · {context}</title>
 {kind==='trend'?<>
 {[0,1,2,3,4].map(i=><g key={i}><line x1="58" x2="704" y1={230-i*42.5} y2={230-i*42.5} stroke="#e7eeeb" strokeDasharray="3 5"/><text x="42" y={234-i*42.5} textAnchor="end" fontSize="12" fill="#7c8e89">{Math.round(max*i/4)}</text></g>)}
 <polygon points={`58,230 ${rows.map(point).join(' ')} 704,230`} fill="#e7f2ed"/><polyline points={rows.map(point).join(' ')} fill="none" stroke="#247b72" strokeWidth="3" strokeLinejoin="round"/>
 {rows.map((r,i)=><g key={r.label}><circle cx={58+i/Math.max(1,rows.length-1)*646} cy={230-r.value/max*170} r={rows.length>60?2:3.5} fill="#247b72"><title>{r.label}：{r.value} 次</title></circle>{(i===0||i===rows.length-1||i%Math.max(1,Math.ceil(rows.length/5))===0)&&<text x={58+i/Math.max(1,rows.length-1)*646} y="263" textAnchor="middle" fontSize="12" fill="#7c8e89">{r.label.slice(5)}</text>}</g>)}<text x="58" y="30" fontSize="12" fill="#7c8e89">打卡次数</text>
 </>:kind==='donut'?<>
 <circle cx="190" cy="145" r="90" fill="none" stroke="#edf3ef" strokeWidth="34"/>
 {rows.map((r,i)=>{const fraction=r.value/total,offset=cumulative;cumulative+=fraction;return <circle key={r.label} cx="190" cy="145" r="90" fill="none" stroke={chartColors[i%chartColors.length]} strokeWidth="34" strokeDasharray={`${fraction*565.49} ${565.49}`} strokeDashoffset={-offset*565.49} transform="rotate(-90 190 145)"><title>{r.label}：{r.value} 次（{(fraction*100).toFixed(1)}%）</title></circle>;})}
 <text x="190" y="145" textAnchor="middle" fontSize="36" fontWeight="700" fill="#203b35">{total}</text><text x="190" y="171" textAnchor="middle" fontSize="13" fill="#7c8e89">打卡记录</text>
 {rows.slice(0,7).map((r,i)=><g key={r.label}><circle cx="362" cy={45+i*32} r="5" fill={chartColors[i%chartColors.length]}/><text x="379" y={50+i*32} fontSize="14" fill="#415d55">{r.label.slice(0,15)}</text><text x="708" y={50+i*32} textAnchor="end" fontSize="14" fill="#203b35">{(r.value/total*100).toFixed(1)}%</text></g>)}{rows.length>7&&<text x="379" y="283" fontSize="12" fill="#7c8e89">完整项目见下方数据明细</text>}
 </>:kind==='histogram'?<>
 {[0,1,2,3,4].map(i=><g key={i}><line x1="58" x2="710" y1={230-i*42.5} y2={230-i*42.5} stroke="#e7eeeb"/><text x="42" y={234-i*42.5} textAnchor="end" fontSize="12" fill="#7c8e89">{Math.round(max*i/4)}</text></g>)}
 {rows.map((r,i)=>{const step=646/Math.max(1,rows.length),width=Math.max(2,Math.min(58,step*.65)),x=58+i*step+(step-width)/2;return <g key={r.label}><rect x={x} y={230-r.value/max*170} width={width} height={r.value/max*170} rx="4" fill="#76aaa0"><title>{r.label}：{r.value} 人</title></rect>{(rows.length<15||i%Math.ceil(rows.length/10)===0)&&<text x={x+width/2} y="256" textAnchor="middle" fontSize="11" fill="#7c8e89">{r.label.replace('运动 ','').replace(' 天','天')}</text>}</g>;})}<text x="58" y="30" fontSize="12" fill="#7c8e89">学生人数</text>
 </>:shown.map((r,i)=><g key={`${r.label}-${i}`}><title>{r.label}：{r.value}</title><text x="18" y={40+i*38} fontSize="13" fill="#415d55">{r.label.length>18?r.label.slice(0,17)+'…':r.label}</text><rect x="200" y={24+i*38} width="450" height="22" rx="5" fill="#f0f5f2"/><rect x="200" y={24+i*38} width={r.value/max*450} height="22" rx="5" fill={chartColors[i%chartColors.length]}/><text x="705" y={40+i*38} textAnchor="end" fontSize="13" fontWeight="600" fill="#203b35">{r.value}</text></g>)}
 <text x="18" y={chartHeight-8} fontSize="10" fill="#91a097">{context}</text></svg></div>:<div className="insights-empty"><span>○</span><p>所选范围暂无数据</p><small>选择其他日期或班级后查看</small></div>}
 {kind==='bars'&&rows.length>8&&<button className="insights-export" onClick={()=>setExpanded(v=>!v)}>{expanded?'收起图表':`展开全部 ${rows.length} 项`}</button>}
 <details className="insights-data"><summary>查看数据明细 <span>{rows.length} 项</span></summary><table className="admin-table"><thead><tr><th>项目</th><th>数量</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.label}</td><td>{r.value}</td></tr>)}</tbody></table></details></section>;
}
export function AdminInsights(){
 const [data,setData]=useState<Insights|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[section,setSection]=useState(''),[revision,setRevision]=useState(0),[classes,setClasses]=useState<{id:string;courseName:string}[]>([]);
 useEffect(()=>{let live=true;void request<{rows:{id:string;courseName:string}[]}>('/admin/course-directory').then(v=>{if(live)setClasses(v.rows);}).catch(e=>{if(live)setError(formatUserFacingError(e));});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;setBusy(true);setError('');setData(null);const q=new URLSearchParams();if(from)q.set('from',from);if(to)q.set('to',to);if(section)q.set('classSectionId',section);void request<Insights>(`/admin/insights?${q}`).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(formatUserFacingError(e));}).finally(()=>{if(live)setBusy(false);});return()=>{live=false;};},[from,to,section,revision]);
 const groups=data?[['每日运动趋势',data.daily],['运动项目分布',data.sports.map(r=>({...r,label:sportLabels[r.label]??r.label}))],['审核状态',data.stages.map(r=>({...r,label:stageLabels[r.label]??r.label}))],['学生运动频率',data.frequency.map(r=>({...r,label:`运动 ${r.label} 天`}))],['班级参与记录',data.classes],['教师审核次数',data.teachers]] as const:[];
 return <div className="admin-insights"><header className="insights-header"><div><span className="insights-eyebrow">SPORTS · ACTIVITY INSIGHTS</span><h2>运动与教学数据看板</h2><p>全局观察运动趋势、班级参与与教师审核。</p></div><div className="insights-live"><i/>真实业务数据</div></header><section className="insights-filter-card"><div className="insights-range">{[7,30,90].map(days=><button key={days} onClick={()=>{const now=new Date();setTo(new Date(now.getTime()+8*3600000).toISOString().slice(0,10));setFrom(new Date(now.getTime()+8*3600000-(days-1)*86400000).toISOString().slice(0,10));}}>近 {days} 天</button>)}<span>自定义日期 · 最长 367 天</span></div><div className="admin-outbox-filters"><label>开始日期<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>结束日期<input type="date" value={to} min={from} onChange={e=>setTo(e.target.value)}/></label><label>班级<select value={section} onChange={e=>setSection(e.target.value)}><option value="">全部班级</option>{classes.map(c=><option key={c.id} value={c.id}>{c.courseName}</option>)}</select></label><button className="secondary-button" disabled={busy} onClick={()=>setRevision(v=>v+1)}>刷新</button><button className="secondary-button" disabled={!data||busy} onClick={()=>{if(!data)return;const cell=(v:string|number)=>'"'+String(v).replace(/^[=+@-]/,"'").replaceAll('"','""')+'"';const lines=[['统计开始','统计结束','图表','项目','数量'],...groups.flatMap(([title,rows])=>rows.map(r=>[data.from,data.to,title,r.label,r.value])),...data.heatmap.map(r=>[data.from,data.to,'运动时段',`周${r.weekday} ${r.hour}:00`,r.value])];download(`运动统计-${data.from}-${data.to}.csv`,'\uFEFF'+lines.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv;charset=utf-8');}}>导出完整数据 CSV</button></div>{error&&<p role="alert">{error}</p>}{busy&&<p role="status">正在汇总数据…</p>}</section>
 {data&&<><div className="insights-kpis">{[['打卡记录',data.summary.records,'次'],['参与学生',data.summary.students,'人'],['实际运动',Number((data.summary.seconds/3600).toFixed(1)),'小时'],['计入学时',Number((data.summary.credited/3600).toFixed(1)),'小时']].map(([label,value,unit])=><section className="insights-kpi" key={label}><span className="insights-kpi-label">{label}</span><strong>{Number(value).toLocaleString()}<small>{unit}</small></strong><div className="insights-kpi-bottom">所选期间累计 <span>↗</span></div></section>)}</div><p className="insights-methodology">范围 {data.from} — {data.to} · 更新于 {businessDateTime(data.generatedAt)}。打卡排除草稿和取消记录；人数按学生去重；频率按有打卡的自然日去重；教师审核按实际审核时间统计，包含重复审核操作。数据不等同于运动质量评价。</p><div className="insights-grid">{groups.map(([title,rows])=><Chart key={title} context={`${data.from} — ${data.to} · ${classes.find(c=>c.id===section)?.courseName??'全部班级'} · 北京时间`} title={title} rows={rows} kind={title==='每日运动趋势'?'trend':title==='运动项目分布'||title==='审核状态'?'donut':title==='学生运动频率'?'histogram':'bars'} note={title==='每日运动趋势'?'每日打卡次数，包含无打卡日期；悬停查看当天数据。':title==='运动项目分布'?'各运动项目占全部打卡的比例。':title==='审核状态'?'所选期间记录的当前审核结果分布。':title==='学生运动频率'?'按有打卡的自然日数分组，展示学生人数。':title==='教师审核次数'?'按审核发生日期统计教师人工审核操作次数。':'横轴为打卡记录数量；覆盖全部筛选结果。'}/>)}</div><section className="insights-card insights-time"><div className="insights-card-heading"><div><span className="insights-eyebrow">WHEN STUDENTS MOVE</span><h3>一周运动时段分布</h3></div><div className="insights-legend">少 <i/><i/><i/> 多</div></div><p className="insights-note">按北京时间的运动开始时刻统计，发现一周中最活跃的时段。悬停查看次数。</p><div className="insights-heatmap">{Array.from({length:7},(_,day)=><div key={day}><b>{['周一','周二','周三','周四','周五','周六','周日'][day]}</b>{Array.from({length:24},(_,hour)=>{const value=data.heatmap.find(r=>r.weekday===day+1&&r.hour===hour)?.value??0,max=Math.max(1,...data.heatmap.map(r=>r.value));return <span key={hour} title={`${hour}:00：${value} 次`} aria-label={`周${day+1} ${hour}点 ${value}次`} style={{background:`rgba(35,132,108,${value?0.2+0.8*value/max:0.05})`}}>{hour}</span>;})}</div>)}</div></section></>}
 </div>;
}
