"use client";
import "./physical-import-panel.css";
import {useEffect,useRef,useState} from "react";
import {ApiError,apiSessionUserId,currentApiSessionEpoch,request,toUserFacingError, formatUserFacingError} from "./api-client";

type Source={studentNumber:string;name:string;runType:string;elapsed:string;testedOn:string};
type Row={rowNumber:number;version:number;source:Source;original:Source;confirmed:boolean;enrollmentId:string|null;issues:string[]};
type Batch={id:string;rows:Row[];pendingCount:number};
type Summary={id:string;createdAt:string;rowCount:number;pendingCount:number};
type Intent={path:string;body:unknown;key:string};
const labels:Record<keyof Source,string>={studentNumber:"学号",name:"姓名",runType:"项目",elapsed:"用时（分:秒）",testedOn:"测试日期"};
const issues:Record<string,string>={STUDENT_NUMBER_NOT_UNIQUE_MATCH:"学号未唯一匹配在课学生",NAME_MISMATCH:"姓名与学生资料不一致",DUPLICATE_STUDENT_ROW:"批次内学号重复",PROJECT_MISMATCH:"项目与学生资料不符",AMBIGUOUS_OR_INVALID_TIME:"用时不明确，请使用分:秒",INVALID_TEST_DATE:"测试日期无效"};
export function PhysicalImportPanel({courseId,onSaved}:{courseId:string;onSaved:()=>void}) {
 const [editing,setEditing]=useState<number|null>(null),[showUpload,setShowUpload]=useState(true);
 const [list,setList]=useState<Summary[]>([]),[before,setBefore]=useState<string|null>(null),[batch,setBatch]=useState<Batch|null>(null);
 const [file,setFile]=useState<File|null>(null),[sheet,setSheet]=useState(""),[selected,setSelected]=useState<number[]>([]);
 const [edits,setEdits]=useState<Record<number,Source>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 const [pending,setPending]=useState<Intent|null>(null),[history,setHistory]=useState<{row:number;items:{version:number;source:Source}[];before:number|null}|null>(null);
 const mounted=useRef(false),lock=useRef(false),epoch=useRef(currentApiSessionEpoch());
 const storageKey=`bnbu:physical-import:${apiSessionUserId()}:${courseId}`,base=`/class-sections/${courseId}/physical-imports`;
 const valid=()=>mounted.current&&epoch.current===currentApiSessionEpoch();
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError("");setMessage("");try{await action();}catch(e){if(valid())setError(formatUserFacingError(e));}finally{lock.current=false;if(valid())setBusy(false);}}
 async function loadList(cursor?:string){const page=await request<{items:Summary[];nextBeforeId:string|null}>(base+`?limit=20${cursor?`&beforeId=${cursor}`:""}`);if(valid()){setList(old=>cursor?[...old,...page.items]:page.items);setBefore(page.nextBeforeId);}}
 function display(value:Batch){setBatch(value);setEditing(null);setShowUpload(false);setSelected([]);setEdits({});setHistory(null);}
 async function load(id:string){const value=await request<Batch>(`/physical-imports/${id}`);if(valid())display(value);}
 useEffect(()=>{mounted.current=true;epoch.current=currentApiSessionEpoch();void run(async()=>{const saved=sessionStorage.getItem(storageKey);if(saved){const value:Intent=JSON.parse(saved);if(!value.key||!(value.path===base||value.path===base+'/xlsx'||/^\/physical-imports\/[0-9a-f-]+\/(confirm|revisions)$/.test(value.path)))throw new Error("导入恢复记录异常，请联系管理员。");setPending(value);}await loadList();});return()=>{mounted.current=false;};},[courseId]);
 async function execute(intent:Intent){
  try{const value=await request<Batch>(intent.path,{method:"POST",body:intent.body,headers:{"Idempotency-Key":intent.key}});if(!valid())return;sessionStorage.removeItem(storageKey);setPending(null);display(value);setMessage(value.pendingCount===0?"本批次已全部确认，体测资料已更新。":`已保存，还有 ${value.pendingCount} 行待核对。`);onSaved();await loadList();}
  catch(e){if(valid()&&e instanceof ApiError&&[403,404,409,422].includes(e.status)){sessionStorage.removeItem(storageKey);setPending(null);}throw e;}
 }
 async function mutate(path:string,body:unknown){if(!valid())return;const intent={path,body,key:crypto.randomUUID()};sessionStorage.setItem(storageKey,JSON.stringify(intent));setPending(intent);await execute(intent);}
 async function upload(){
  if(!file)throw new Error("请选择 CSV 或 XLSX 文件。");if(file.size>1048576)throw new Error("当前电子体测接口支持不超过 1 MiB 的文件。");
  const bytes=new Uint8Array(await file.arrayBuffer());if(!valid())return;
  if(/\.csv$/i.test(file.name)){const csv=new TextDecoder("utf-8",{fatal:true}).decode(bytes);await mutate(base,{csv});}
  else if(/\.xlsx$/i.test(file.name)){if(!sheet.trim())throw new Error("请填写要导入的工作表名称。");let binary="";for(const byte of bytes)binary+=String.fromCharCode(byte);await mutate(base+'/xlsx',{fileBase64:btoa(binary),sheetName:sheet.trim()});}
  else throw new Error("仅支持 UTF-8 CSV 和 XLSX。");
 }
 async function confirm(){if(!batch||!selected.length)return;const selections=[];for(const row of batch.rows.filter(r=>selected.includes(r.rowNumber))){if(row.confirmed||row.issues.length||!row.enrollmentId||edits[row.rowNumber])throw new Error("请先保存并核对所选行。");const latest=await request<{items:{version:number}[]}>(`/enrollments/${row.enrollmentId}/physical-results?limit=1`);if(!valid())return;selections.push({rowNumber:row.rowNumber,expectedVersion:row.version,expectedResultVersion:latest.items[0]?.version??0});}await mutate(`/physical-imports/${batch.id}/confirm`,{selections});}
 async function source(){if(!batch)return;const value=await request<{csv?:string;fileBase64?:string}>(`/physical-imports/${batch.id}/source`);if(!valid())return;const xlsx=value.fileBase64!==undefined;const bytes=xlsx?Uint8Array.from(atob(value.fileBase64!),c=>c.charCodeAt(0)):value.csv!;const url=URL.createObjectURL(new Blob([bytes],{type:xlsx?"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":"text/csv;charset=utf-8"}));const a=document.createElement('a');a.href=url;a.download=`physical-${batch.id}.${xlsx?'xlsx':'csv'}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 async function revisions(row:number,cursor?:number){if(!batch)return;const value=await request<{items:{version:number;source:Source}[];nextBeforeVersion:number|null}>(`/physical-imports/${batch.id}/revisions?rowNumber=${row}&limit=20${cursor?`&beforeVersion=${cursor}`:""}`);if(valid())setHistory(old=>({row,items:cursor&&old?.row===row?[...old.items,...value.items]:value.items,before:value.nextBeforeVersion}));}
 const disabled=busy||!!pending;
 const dirty=Object.keys(edits).length>0;
 const ready=batch?.rows.filter(row=>!row.confirmed&&!row.issues.length)??[];
 const editRow=batch?.rows.find(row=>row.rowNumber===editing);
 return <details className="physical-import"><summary>电子体测成绩导入与核对<span>CSV / Excel</span></summary>
  <div className="physical-import-body">
   <ol className="physical-import-steps" aria-label="体测导入流程"><li className={!batch?"current":"done"}>1 上传文件</li><li className={batch?.pendingCount?"current":""}>2 核对数据</li><li className={batch?.pendingCount===0?"current":""}>3 确认入库</li></ol>
   {error&&<p className="physical-import-notice error" role="alert">{error}</p>}{message&&<p className="physical-import-notice" role="status">{message}</p>}
   {pending&&<div className="physical-import-notice" role="status"><p>{busy?"正在保存，请稍候…":"上次提交结果待确认，请重试原操作。"}</p><button className="secondary-button" type="button" disabled={busy} onClick={()=>void run(()=>execute(pending))}>重试原操作</button></div>}
   <div className="physical-import-toolbar"><button className="secondary-button" type="button" disabled={disabled||dirty} onClick={()=>setShowUpload(!showUpload)}>{showUpload?"收起上传":"导入新文件"}</button><details className="physical-import-batches"><summary>历史导入 · {list.length} 批</summary><div>{list.length===0&&<p>暂无导入记录</p>}{list.map(item=><button className={batch?.id===item.id?"selected":""} type="button" key={item.id} disabled={disabled||dirty} onClick={()=>void run(()=>load(item.id))}><span>{new Date(item.createdAt).toLocaleString()}</span><small>{item.rowCount} 行 · {item.pendingCount?`待核对 ${item.pendingCount} 行`:"全部已确认"}</small></button>)}<button type="button" disabled={disabled} onClick={()=>void run(()=>loadList())}>刷新记录</button>{before&&<button type="button" disabled={disabled} onClick={()=>void run(()=>loadList(before))}>加载更早批次</button>}</div></details></div>
   {showUpload&&<section className="physical-import-upload" aria-label="上传体测文件"><h4>导入电子成绩单</h4><p>选择 CSV 或 Excel 文件。先核对内容，再由你确认保存。</p><label className="physical-import-file">选择电子体测文件<input type="file" accept=".csv,.xlsx" disabled={disabled||dirty} onChange={e=>setFile(e.target.files?.[0]??null)}/></label><small>支持 UTF-8 CSV、XLSX，单文件不超过 1 MiB。</small>{file&&/\.xlsx$/i.test(file.name)&&<label>工作表名称<input placeholder="例如：体测" value={sheet} maxLength={31} disabled={disabled} onChange={e=>setSheet(e.target.value)}/></label>}<details><summary>查看文件格式要求</summary><p>表头：学号、姓名、项目、用时、测试日期</p><p>示例：9900000002 / TEST BETA / 1000m / 5:10 / 2026-09-12</p><p>用时使用“分:秒”；日期使用“年-月-日”。Excel 需填写要导入的工作表名称。</p></details><button className="primary-button" type="button" disabled={disabled||dirty||!file} onClick={()=>void run(upload)}>{busy?"正在处理…":"上传并核对"}</button></section>}
   {batch&&<section aria-label="电子体测核对"><div className="physical-import-review-head"><div><h4>核对本批成绩</h4><p>{batch.rows.length} 行 · 待核对 {batch.pendingCount} 行 · 已确认 {batch.rows.length-batch.pendingCount} 行</p></div><button className="text-button" type="button" disabled={disabled} onClick={()=>void run(source)}>下载原始文件</button></div>
    <div className="physical-import-toolbar"><button className="secondary-button" type="button" disabled={disabled||dirty||!ready.length} onClick={()=>setSelected(ready.map(row=>row.rowNumber))}>选择全部可确认行（{ready.length}）</button><button className="text-button" type="button" disabled={disabled||!selected.length} onClick={()=>setSelected([])}>取消选择</button><button className="text-button" type="button" disabled={disabled||dirty} onClick={()=>void run(()=>load(batch.id))}>刷新数据</button></div>
    <div className="physical-import-table-wrap"><table><caption className="sr-only">体测导入核对表</caption><thead><tr><th>选择</th><th>学生</th><th>项目 / 用时</th><th>测试日期</th><th>状态</th><th>操作</th></tr></thead><tbody>{batch.rows.map(row=><tr key={row.rowNumber} className={row.confirmed?"confirmed":row.issues.length?"needs-review":""}><td><input type="checkbox" aria-label={`选择第 ${row.rowNumber} 行确认`} checked={selected.includes(row.rowNumber)} disabled={disabled||dirty||row.confirmed||row.issues.length>0} onChange={e=>setSelected(old=>e.target.checked?[...old,row.rowNumber]:old.filter(n=>n!==row.rowNumber))}/></td><td><strong>{row.source.name||"姓名未填写"}</strong><small>{row.source.studentNumber||"学号未填写"}</small></td><td>{row.source.runType}<small>{row.source.elapsed}</small></td><td>{row.source.testedOn}</td><td><span className={`physical-import-state ${row.confirmed?"saved":row.issues.length?"warning":"ready"}`}>{row.confirmed?"已确认":row.issues.length?"需修正":"可确认"}</span>{row.issues.length>0&&<small className="physical-import-issues">{row.issues.map(issue=>issues[issue]??"请核对该行").join("；")}</small>}</td><td><button className="text-button" type="button" disabled={disabled||dirty||row.confirmed} onClick={()=>{setEditing(row.rowNumber);setEdits({[row.rowNumber]:{...row.source}});setSelected([]);setHistory(null);}}>修正</button><button className="text-button" type="button" disabled={disabled||dirty} onClick={()=>void run(()=>revisions(row.rowNumber))}>历史</button></td></tr>)}</tbody></table></div>
    {editRow&&<section className="physical-import-editor" aria-label={`修正第 ${editRow.rowNumber} 行`}><h4>修正第 {editRow.rowNumber} 行</h4><p>原始内容：{(Object.keys(labels) as (keyof Source)[]).map(field=>`${labels[field]}：${editRow.original[field]}`).join(" · ")}</p><div>{(Object.keys(labels) as (keyof Source)[]).map(field=><label key={field}>{labels[field]}<input disabled={disabled} value={(edits[editRow.rowNumber]??editRow.source)[field]} onChange={e=>{const value=e.target.value;setEdits(old=>({...old,[editRow.rowNumber]:{...(old[editRow.rowNumber]??editRow.source),[field]:value}}));}}/></label>)}</div><div className="physical-import-toolbar"><button className="primary-button" type="button" disabled={disabled} onClick={()=>void run(()=>mutate(`/physical-imports/${batch.id}/revisions`,{...edits[editRow.rowNumber],rowNumber:editRow.rowNumber,expectedVersion:editRow.version}))}>保存修正</button><button className="secondary-button" type="button" disabled={disabled} onClick={()=>{setEditing(null);setEdits({});}}>取消编辑</button></div></section>}
    {history&&<section className="physical-import-history"><div className="physical-import-review-head"><h4>第 {history.row} 行 · 修订历史</h4><button className="text-button" type="button" onClick={()=>setHistory(null)}>收起历史</button></div>{history.items.map(item=><p key={item.version}><strong>版本 {item.version}</strong> · {(Object.keys(labels) as (keyof Source)[]).map(field=>item.source[field]).join(" / ")}</p>)}{history.before&&<button className="text-button" type="button" disabled={disabled} onClick={()=>void run(()=>revisions(history.row,history.before!))}>加载更早修订</button>}</section>}
    <div className="physical-import-confirm"><div><strong>{batch.pendingCount===0?"本批次已全部确认":`已选 ${selected.length} 行`}</strong><p>{dirty?"请先保存或取消当前行的修正。":batch.pendingCount===0?"体测资料已更新，历史版本会保留。":"仅保存勾选的行，其他行可稍后处理。"}</p></div><button className="primary-button" type="button" disabled={disabled||dirty||!selected.length} onClick={()=>void run(confirm)}>{busy?"正在保存…":`确认入库（${selected.length}）`}</button></div>
   </section>}
  </div>
 </details>;
}
