-- Preserve business/audit identity references while current account data can be removed.
-- Explicit constraints from the verified 0046 local schema. No row deletion or CASCADE added.
BEGIN;
ALTER TABLE "audit_logs" DROP CONSTRAINT "audit_logs_actor_user_id_organization_id_fkey";
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "class_section_excluded_dates" DROP CONSTRAINT "class_section_excluded_dates_created_by_organization_id_fkey";
ALTER TABLE "class_section_excluded_dates" ADD CONSTRAINT "class_section_excluded_dates_created_by_organization_id_fkey" FOREIGN KEY (created_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "class_sections" DROP CONSTRAINT "class_sections_closed_by_organization_id_fkey";
ALTER TABLE "class_sections" ADD CONSTRAINT "class_sections_closed_by_organization_id_fkey" FOREIGN KEY (closed_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "class_sections" DROP CONSTRAINT "class_sections_created_by_organization_id_fkey";
ALTER TABLE "class_sections" ADD CONSTRAINT "class_sections_created_by_organization_id_fkey" FOREIGN KEY (created_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "class_sections" DROP CONSTRAINT "class_sections_teacher_id_organization_id_fkey";
ALTER TABLE "class_sections" ADD CONSTRAINT "class_sections_teacher_id_organization_id_fkey" FOREIGN KEY (teacher_id, organization_id) REFERENCES v81_teacher_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "class_sections" DROP CONSTRAINT "class_sections_updated_by_organization_id_fkey";
ALTER TABLE "class_sections" ADD CONSTRAINT "class_sections_updated_by_organization_id_fkey" FOREIGN KEY (updated_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "course_invites" DROP CONSTRAINT "course_invites_created_by_organization_id_fkey";
ALTER TABLE "course_invites" ADD CONSTRAINT "course_invites_created_by_organization_id_fkey" FOREIGN KEY (created_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "course_invites" DROP CONSTRAINT "course_invites_revoked_by_organization_id_fkey";
ALTER TABLE "course_invites" ADD CONSTRAINT "course_invites_revoked_by_organization_id_fkey" FOREIGN KEY (revoked_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "courses" DROP CONSTRAINT "courses_created_by_organization_id_fkey";
ALTER TABLE "courses" ADD CONSTRAINT "courses_created_by_organization_id_fkey" FOREIGN KEY (created_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "courses" DROP CONSTRAINT "courses_deleted_by_organization_id_fkey";
ALTER TABLE "courses" ADD CONSTRAINT "courses_deleted_by_organization_id_fkey" FOREIGN KEY (deleted_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "courses" DROP CONSTRAINT "courses_updated_by_organization_id_fkey";
ALTER TABLE "courses" ADD CONSTRAINT "courses_updated_by_organization_id_fkey" FOREIGN KEY (updated_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "enrollment_status_events" DROP CONSTRAINT "enrollment_status_events_actor_user_id_organization_id_fkey";
ALTER TABLE "enrollment_status_events" ADD CONSTRAINT "enrollment_status_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_created_by_organization_id_fkey";
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_created_by_organization_id_fkey" FOREIGN KEY (created_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_student_id_organization_id_fkey";
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_student_id_organization_id_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "enrollments" DROP CONSTRAINT "enrollments_updated_by_organization_id_fkey";
ALTER TABLE "enrollments" ADD CONSTRAINT "enrollments_updated_by_organization_id_fkey" FOREIGN KEY (updated_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "exemption_application_events" DROP CONSTRAINT "exemption_application_events_actor_user_id_organization_id_fkey";
ALTER TABLE "exemption_application_events" ADD CONSTRAINT "exemption_application_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "exemption_applications" DROP CONSTRAINT "exemption_applications_student_id_organization_id_fkey";
ALTER TABLE "exemption_applications" ADD CONSTRAINT "exemption_applications_student_id_organization_id_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "exemption_review_records" DROP CONSTRAINT "exemption_review_records_teacher_id_organization_id_fkey";
ALTER TABLE "exemption_review_records" ADD CONSTRAINT "exemption_review_records_teacher_id_organization_id_fkey" FOREIGN KEY (teacher_id, organization_id) REFERENCES v81_teacher_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "exercise_record_events" DROP CONSTRAINT "exercise_record_events_actor_organization_fkey";
ALTER TABLE "exercise_record_events" ADD CONSTRAINT "exercise_record_events_actor_organization_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "exercise_records" DROP CONSTRAINT "exercise_records_student_organization_fkey";
ALTER TABLE "exercise_records" ADD CONSTRAINT "exercise_records_student_organization_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "exercise_records" DROP CONSTRAINT "exercise_records_teacher_organization_fkey";
ALTER TABLE "exercise_records" ADD CONSTRAINT "exercise_records_teacher_organization_fkey" FOREIGN KEY (teacher_id, organization_id) REFERENCES v81_teacher_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "exercise_session_events" DROP CONSTRAINT "exercise_session_events_actor_organization_fkey";
ALTER TABLE "exercise_session_events" ADD CONSTRAINT "exercise_session_events_actor_organization_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "exercise_sessions" DROP CONSTRAINT "exercise_sessions_student_organization_fkey";
ALTER TABLE "exercise_sessions" ADD CONSTRAINT "exercise_sessions_student_organization_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "feedback" DROP CONSTRAINT "feedback_created_by_user_id_organization_id_fkey";
ALTER TABLE "feedback" ADD CONSTRAINT "feedback_created_by_user_id_organization_id_fkey" FOREIGN KEY (created_by_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "feedback_events" DROP CONSTRAINT "feedback_events_actor_user_id_organization_id_fkey";
ALTER TABLE "feedback_events" ADD CONSTRAINT "feedback_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "location_consent_events" DROP CONSTRAINT "location_consent_events_actor_user_id_organization_id_fkey";
ALTER TABLE "location_consent_events" ADD CONSTRAINT "location_consent_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "location_consents" DROP CONSTRAINT "location_consents_student_id_organization_id_fkey";
ALTER TABLE "location_consents" ADD CONSTRAINT "location_consents_student_id_organization_id_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "location_privacy_policies" DROP CONSTRAINT "location_privacy_policies_created_by_user_id_organization__fkey";
ALTER TABLE "location_privacy_policies" ADD CONSTRAINT "location_privacy_policies_created_by_user_id_organization__fkey" FOREIGN KEY (created_by_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "location_track_events" DROP CONSTRAINT "location_track_events_actor_user_id_organization_id_fkey";
ALTER TABLE "location_track_events" ADD CONSTRAINT "location_track_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "location_tracks" DROP CONSTRAINT "location_tracks_student_id_organization_id_fkey";
ALTER TABLE "location_tracks" ADD CONSTRAINT "location_tracks_student_id_organization_id_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "media_evidence" DROP CONSTRAINT "media_evidence_initiator_organization_fkey";
ALTER TABLE "media_evidence" ADD CONSTRAINT "media_evidence_initiator_organization_fkey" FOREIGN KEY (initiated_by_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "media_evidence" DROP CONSTRAINT "media_evidence_owner_organization_fkey";
ALTER TABLE "media_evidence" ADD CONSTRAINT "media_evidence_owner_organization_fkey" FOREIGN KEY (owner_student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "notification_events" DROP CONSTRAINT "notification_events_actor_user_id_organization_id_fkey";
ALTER TABLE "notification_events" ADD CONSTRAINT "notification_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "notifications" DROP CONSTRAINT "notifications_recipient_user_id_organization_id_fkey";
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_recipient_user_id_organization_id_fkey" FOREIGN KEY (recipient_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "official_roster_imports" DROP CONSTRAINT "official_roster_imports_imported_by_organization_id_fkey";
ALTER TABLE "official_roster_imports" ADD CONSTRAINT "official_roster_imports_imported_by_organization_id_fkey" FOREIGN KEY (imported_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "push_device_events" DROP CONSTRAINT "push_device_events_actor_user_id_organization_id_fkey";
ALTER TABLE "push_device_events" ADD CONSTRAINT "push_device_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "review_records" DROP CONSTRAINT "review_records_teacher_organization_fkey";
ALTER TABLE "review_records" ADD CONSTRAINT "review_records_teacher_organization_fkey" FOREIGN KEY (teacher_id, organization_id) REFERENCES v81_teacher_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "roster_alignment_platform_entries" DROP CONSTRAINT "roster_platform_entries_student_organization_fkey";
ALTER TABLE "roster_alignment_platform_entries" ADD CONSTRAINT "roster_platform_entries_student_organization_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "roster_alignment_results" DROP CONSTRAINT "roster_alignment_results_resolved_by_organization_fkey";
ALTER TABLE "roster_alignment_results" ADD CONSTRAINT "roster_alignment_results_resolved_by_organization_fkey" FOREIGN KEY (resolved_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "roster_alignment_runs" DROP CONSTRAINT "roster_alignment_runs_started_by_organization_id_fkey";
ALTER TABLE "roster_alignment_runs" ADD CONSTRAINT "roster_alignment_runs_started_by_organization_id_fkey" FOREIGN KEY (started_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "roster_resolution_events" DROP CONSTRAINT "roster_resolution_events_actor_organization_fkey";
ALTER TABLE "roster_resolution_events" ADD CONSTRAINT "roster_resolution_events_actor_organization_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "score_adjustment_approval_events" DROP CONSTRAINT "score_adjustment_approval_events_actor_user_id_organizatio_fkey";
ALTER TABLE "score_adjustment_approval_events" ADD CONSTRAINT "score_adjustment_approval_events_actor_user_id_organizatio_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "score_adjustments" DROP CONSTRAINT "score_adjustments_requested_by_organization_id_fkey";
ALTER TABLE "score_adjustments" ADD CONSTRAINT "score_adjustments_requested_by_organization_id_fkey" FOREIGN KEY (requested_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "score_adjustments" DROP CONSTRAINT "score_adjustments_student_id_organization_id_fkey";
ALTER TABLE "score_adjustments" ADD CONSTRAINT "score_adjustments_student_id_organization_id_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "score_publication_events" DROP CONSTRAINT "score_publication_events_actor_user_id_organization_id_fkey";
ALTER TABLE "score_publication_events" ADD CONSTRAINT "score_publication_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "score_rule_approval_events" DROP CONSTRAINT "score_rule_approval_events_actor_user_id_organization_id_fkey";
ALTER TABLE "score_rule_approval_events" ADD CONSTRAINT "score_rule_approval_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "score_rules" DROP CONSTRAINT "score_rules_created_by_organization_id_fkey";
ALTER TABLE "score_rules" ADD CONSTRAINT "score_rules_created_by_organization_id_fkey" FOREIGN KEY (created_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "semesters" DROP CONSTRAINT "semesters_created_by_organization_id_fkey";
ALTER TABLE "semesters" ADD CONSTRAINT "semesters_created_by_organization_id_fkey" FOREIGN KEY (created_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "student_scores" DROP CONSTRAINT "student_scores_student_id_organization_id_fkey";
ALTER TABLE "student_scores" ADD CONSTRAINT "student_scores_student_id_organization_id_fkey" FOREIGN KEY (student_id, organization_id) REFERENCES v81_student_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "system_policies" DROP CONSTRAINT "system_policies_changed_by_organization_id_fkey";
ALTER TABLE "system_policies" ADD CONSTRAINT "system_policies_changed_by_organization_id_fkey" FOREIGN KEY (changed_by, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "user_preference_events" DROP CONSTRAINT "user_preference_events_actor_user_id_organization_id_fkey";
ALTER TABLE "user_preference_events" ADD CONSTRAINT "user_preference_events_actor_user_id_organization_id_fkey" FOREIGN KEY (actor_user_id, organization_id) REFERENCES v81_user_subjects(id, organization_id) ON UPDATE CASCADE ON DELETE RESTRICT;
ALTER TABLE "v81_confirmed_rosters" DROP CONSTRAINT "v81_confirmed_rosters_actor_id_fkey";
ALTER TABLE "v81_confirmed_rosters" ADD CONSTRAINT "v81_confirmed_rosters_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_endurance_table_revisions" DROP CONSTRAINT "v81_endurance_table_revisions_actor_id_organization_id_fkey";
ALTER TABLE "v81_endurance_table_revisions" ADD CONSTRAINT "v81_endurance_table_revisions_actor_id_organization_id_fkey" FOREIGN KEY (actor_id, organization_id) REFERENCES v81_user_subjects(id, organization_id);
ALTER TABLE "v81_final_grade_revisions" DROP CONSTRAINT "v81_final_grade_revisions_actor_id_fkey";
ALTER TABLE "v81_final_grade_revisions" ADD CONSTRAINT "v81_final_grade_revisions_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id) ON DELETE RESTRICT;
ALTER TABLE "v81_help_article_revisions" DROP CONSTRAINT "v81_help_article_revisions_actor_id_organization_id_fkey";
ALTER TABLE "v81_help_article_revisions" ADD CONSTRAINT "v81_help_article_revisions_actor_id_organization_id_fkey" FOREIGN KEY (actor_id, organization_id) REFERENCES v81_user_subjects(id, organization_id);
ALTER TABLE "v81_makeup_revocations" DROP CONSTRAINT "v81_makeup_revocations_actor_id_fkey";
ALTER TABLE "v81_makeup_revocations" ADD CONSTRAINT "v81_makeup_revocations_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_makeup_windows" DROP CONSTRAINT "v81_makeup_windows_actor_id_fkey";
ALTER TABLE "v81_makeup_windows" ADD CONSTRAINT "v81_makeup_windows_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_ocr_batches" DROP CONSTRAINT "v81_ocr_batches_actor_id_organization_id_fkey";
ALTER TABLE "v81_ocr_batches" ADD CONSTRAINT "v81_ocr_batches_actor_id_organization_id_fkey" FOREIGN KEY (actor_id, organization_id) REFERENCES v81_user_subjects(id, organization_id);
ALTER TABLE "v81_ocr_draft_revisions" DROP CONSTRAINT "v81_ocr_draft_revisions_actor_id_fkey";
ALTER TABLE "v81_ocr_draft_revisions" ADD CONSTRAINT "v81_ocr_draft_revisions_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_ocr_jobs" DROP CONSTRAINT "v81_ocr_jobs_actor_id_organization_id_fkey";
ALTER TABLE "v81_ocr_jobs" ADD CONSTRAINT "v81_ocr_jobs_actor_id_organization_id_fkey" FOREIGN KEY (actor_id, organization_id) REFERENCES v81_user_subjects(id, organization_id);
ALTER TABLE "v81_ocr_physical_confirmations" DROP CONSTRAINT "v81_ocr_physical_confirmations_actor_id_fkey";
ALTER TABLE "v81_ocr_physical_confirmations" ADD CONSTRAINT "v81_ocr_physical_confirmations_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_physical_import_batches" DROP CONSTRAINT "v81_physical_import_batches_actor_id_fkey";
ALTER TABLE "v81_physical_import_batches" ADD CONSTRAINT "v81_physical_import_batches_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_physical_import_row_revisions" DROP CONSTRAINT "v81_physical_import_row_revisions_actor_id_fkey";
ALTER TABLE "v81_physical_import_row_revisions" ADD CONSTRAINT "v81_physical_import_row_revisions_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_physical_result_revisions" DROP CONSTRAINT "v81_physical_result_revisions_actor_id_fkey";
ALTER TABLE "v81_physical_result_revisions" ADD CONSTRAINT "v81_physical_result_revisions_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_rule_templates" DROP CONSTRAINT "v81_rule_templates_actor_id_fkey";
ALTER TABLE "v81_rule_templates" ADD CONSTRAINT "v81_rule_templates_actor_id_fkey" FOREIGN KEY (actor_id) REFERENCES v81_user_subjects(id);
ALTER TABLE "v81_runtime_archives" DROP CONSTRAINT "v81_runtime_archives_requester_id_organization_id_fkey";
ALTER TABLE "v81_runtime_archives" ADD CONSTRAINT "v81_runtime_archives_requester_id_organization_id_fkey" FOREIGN KEY (requester_id, organization_id) REFERENCES v81_user_subjects(id, organization_id);
COMMIT;
