import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import { loadRuntimeSecrets } from '/app/dist/common/config/file-json-secret-loader.js';
import { validateEnvironment } from '/app/dist/common/config/environment.js';
import { S3MediaStorageAdapter } from '/app/dist/common/object-storage/s3-media-storage.adapter.js';
import { scannedMediaStream } from '/app/dist/modules/media/application/clamav-stream.js';
await loadRuntimeSecrets(process.env);
const config=validateEnvironment(process.env).RUNTIME_CONFIG;
const adapter=new S3MediaStorageAdapter(config);
const report=[];
const pass=(check,details={})=>report.push({check,status:'PASS',...details});
try {
  const initial=JSON.parse(await readFile('/bootstrap/initial-admin.json','utf8'));
  const base='https://www.teacher.bnbusports.cn/api/v1';
  const login=await fetch(`${base}/auth/password-login`,{method:'POST',headers:{'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({account:initial.email,password:initial.password})});
  const payload=await login.json();
  assert.equal(login.status,200,JSON.stringify({status:login.status,error:payload.error}));
  assert.equal(payload.data.user.role,'ADMIN');
  pass('formal-https-admin-password-login');
  const headers={authorization:`Bearer ${payload.data.accessToken}`};
  const security=await fetch(`${base}/auth/account-security`,{headers});
  const state=await security.json();
  assert.equal(security.status,200);
  assert.equal(state.data.mustChangePassword,true);
  pass('initial-admin-first-password-change-required');
  const denied=await fetch(`${base}/admin/subadmins`,{headers});
  assert.equal(denied.status,403);
  pass('initial-admin-business-access-denied-before-password-change');
  await adapter.checkHealth();
  const key=`media/${initial.organizationId}/${randomUUID()}/image`;
  const bytes=Buffer.from('BNBU production synthetic COS roundtrip; no personal data.');
  const upload=await adapter.createUploadUrl({storageKey:key,contentType:'application/octet-stream',contentLength:bytes.length,expiresInSeconds:120});
  const put=await fetch(upload.url,{method:upload.method,headers:upload.requiredHeaders,body:bytes});
  assert.equal(put.status,200);
  const meta=await adapter.headPrivateObject(key);assert.equal(meta.contentLength,bytes.length);
  const chunks=[];
  for await(const chunk of scannedMediaStream(await adapter.getPrivateObject(key),'/run/clamav/clamd.ctl'))chunks.push(Buffer.from(chunk));
  assert.ok(Buffer.concat(chunks).equals(bytes));
  pass('production-role-COS-put-head-get-real-scanner', {syntheticObjectKey:key});
  const signed=await adapter.createAccessUrl({storageKey:key,contentType:'application/octet-stream',expiresInSeconds:120});
  const downloaded=await fetch(signed);assert.equal(downloaded.status,200);assert.ok(Buffer.from(await downloaded.arrayBuffer()).equals(bytes));
  pass('COS-signed-https-byte-roundtrip');
  const unsigned=new URL(signed);unsigned.search='';
  assert.equal((await fetch(unsigned)).status,403);pass('COS-anonymous-access-denied');
  const cors=await fetch(unsigned,{method:'OPTIONS',headers:{origin:'https://www.student.bnbusports.cn','access-control-request-method':'PUT','access-control-request-headers':'content-type'}});
  assert.equal(cors.status,200);assert.equal(cors.headers.get('access-control-allow-origin'),'https://www.student.bnbusports.cn');pass('COS-production-origin-CORS');
  const logout=await fetch(`${base}/auth/logout`,{method:'POST',headers:{...headers,'content-type':'application/json','idempotency-key':randomUUID()},body:JSON.stringify({refreshToken:payload.data.refreshToken})});
  assert.equal(logout.status,200);pass('admin-session-logout');
  console.log(JSON.stringify(report));
} finally {adapter.onModuleDestroy();}
